
/**
 * Comprehensive list of programming languages with their file extensions
 * This is used when the API fails to load languages
 */
const PROGRAMMING_LANGUAGES = [
  { name: "JavaScript", extension: "js", hljs: "javascript", popular: true },
  { name: "TypeScript", extension: "ts", hljs: "typescript", popular: true },
  { name: "Python", extension: "py", hljs: "python", popular: true },
  { name: "Java", extension: "java", hljs: "java", popular: true },
  { name: "C#", extension: "cs", hljs: "csharp", popular: true },
  { name: "C++", extension: "cpp", hljs: "cpp", popular: true },
  { name: "C", extension: "c", hljs: "c", popular: true },
  { name: "PHP", extension: "php", hljs: "php", popular: true },
  { name: "Ruby", extension: "rb", hljs: "ruby", popular: true },
  { name: "Go", extension: "go", hljs: "go", popular: true },
  { name: "Rust", extension: "rs", hljs: "rust", popular: true },
  { name: "Swift", extension: "swift", hljs: "swift", popular: true },
  { name: "Kotlin", extension: "kt", hljs: "kotlin", popular: true },
  { name: "SQL", extension: "sql", hljs: "sql", popular: true },
  { name: "Bash/Shell", extension: "sh", hljs: "bash", popular: true },
  { name: "HTML", extension: "html", hljs: "html", popular: true },
  { name: "CSS", extension: "css", hljs: "css", popular: true },
  // Additional languages
  { name: "SCSS", extension: "scss", hljs: "scss" },
  { name: "LESS", extension: "less", hljs: "less" },
  { name: "Dart", extension: "dart", hljs: "dart" },
  { name: "PowerShell", extension: "ps1", hljs: "powershell" },
  { name: "R", extension: "r", hljs: "r" },
  { name: "Perl", extension: "pl", hljs: "perl" },
  { name: "Lua", extension: "lua", hljs: "lua" },
  { name: "Groovy", extension: "groovy", hljs: "groovy" },
  { name: "Scala", extension: "scala", hljs: "scala" },
  { name: "Objective-C", extension: "m", hljs: "objectivec" },
  { name: "Haskell", extension: "hs", hljs: "haskell" },
  { name: "Clojure", extension: "clj", hljs: "clojure" },
  { name: "Elixir", extension: "ex", hljs: "elixir" },
  { name: "F#", extension: "fs", hljs: "fsharp" },
  { name: "Julia", extension: "jl", hljs: "julia" },
  { name: "Assembly", extension: "asm", hljs: "assembly" },
  { name: "COBOL", extension: "cbl", hljs: "cobol" },
  { name: "Fortran", extension: "f90", hljs: "fortran" },
  { name: "MATLAB", extension: "m", hljs: "matlab" },
  { name: "Visual Basic", extension: "vb", hljs: "vbnet" },
  { name: "Lisp", extension: "lisp", hljs: "lisp" },
  { name: "Prolog", extension: "pl", hljs: "prolog" },
  { name: "JSON", extension: "json", hljs: "json" },
  { name: "YAML", extension: "yaml", hljs: "yaml" },
  { name: "XML", extension: "xml", hljs: "xml" },
  { name: "Markdown", extension: "md", hljs: "markdown" },
  { name: "LaTeX", extension: "tex", hljs: "latex" },
  { name: "GraphQL", extension: "graphql", hljs: "graphql" },
  { name: "Solidity", extension: "sol", hljs: "solidity" },
  { name: "Erlang", extension: "erl", hljs: "erlang" },
  { name: "WebAssembly", extension: "wasm", hljs: "wasm" },
  { name: "Dockerfile", extension: "dockerfile", hljs: "dockerfile" },
];

export default PROGRAMMING_LANGUAGES;
